Заигнорил папку `data/`, названия датасетов не менял.

`main_test.py` - решатель для кр на 8/10

**UPD:** добавил новый решатель кр `main_test.ipynb` - результат 9-10/11 
